# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, std-msgs }:
buildRosPackage rec {
  pname = "ros-humble-ros2-interfaces-pkg";
  version = "1.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ geometry-msgs rosidl-default-runtime std-msgs ];
  nativeBuildInputs = [ ament-cmake rosidl-default-generators ];

  meta = {
    description = "ASTRA's custom ROS2 message types.";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
